# docker-compose.yml
version: '3.8'

services:

  nginx:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
