# docker-compose.yml

version: '3.8'

services:

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
