# docker-compose.yml
version: '3.8'

services:

  user_service:
    build:
      context: ./todo_user_service
    container_name: todo_user_service
    ports:
      - "5001:5001"
    networks:
      - app-network

  task_service:
    build:
      context: ./task_service
    container_name: task_service
    ports:
      - "5003:5003"
    networks:
      - app-network

  nginx:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
